apiVersion: v1
kind: Service
metadata:
  name: legacy-service

spec:
  selector:
    app: legacy

  ports:
    - name: http
      port: 8080

  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service

spec:
  selector:
    app: webapp

  ports:
    - name: http
      port: 8080
      nodePort: 30080

  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-deployment
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: legacy
  template:
    metadata:
      labels:
        app: legacy
    spec:
      containers:
      - name: timetracker
        image: alirizasaral/timetracker:1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  minReadySeconds: 60
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: timetracker-bff
        image: timetracker/timetracker-bff:0.0.1-SNAPSHOT
        env:
          - name: LEGACY_SERVICE_URL
            value: http://legacy-service:8080
